'use client'

import TopNavbar from "@/components/TopNavbar"
import { useEffect, useState } from "react";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const getUserFromLocalStorage = (): User | null => {
    // ดึงข้อมูลจาก localStorage ตามคีย์ที่กำหนด เช่น 'user'
    const storedUser = localStorage.getItem('user');
  
    // ถ้าไม่มีข้อมูล ให้คืนค่าเป็น null
    if (!storedUser) return null;
  
    // แปลง JSON เป็น object และ return object ของ User
    try {
      const user: User = JSON.parse(storedUser);
      return user;
    } catch (error) {
      console.error('Error parsing user data:', error);
      return null;
    }
  };

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {

    const [user, setUser] = useState<User | null>(null);

    useEffect(() => {
      const storedUser = getUserFromLocalStorage();
      setUser(storedUser);
    }, []);

    return (
        <html lang="en">
            <body>
                <TopNavbar  currentUser={user ? (user.staff_name): ("-")}/>
                {children}
            </body>
        </html>
  )
}
