import TopNavbar from "@/components/TopNavbar"


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <footer className="text-center">
          bye
        </footer>
      </body>
    </html>
  )
}
