import '@/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="th">
      <head>
          <meta charSet="UTF-8" />
        </head>
      <body>
        {children}
      </body>
    </html>
  )
}
