import '@/globals.css'

import type { AppProps } from 'next/app'
import { UserProvider } from '../context/UserContext'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
      <body>
        {children}
      </body>
      </UserProvider>
    </html>
  )
}
